name: fast_rx_test
description: Testing utilities for fast_rx. Check for valid rx registration and notifications.
version: 0.4.0
homepage: https://github.com/Rexios80/fast_ui/tree/master/fast_rx_test

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fast_rx: ^0.4.0
  test: ^1.19.0

dev_dependencies:
  rexios_lints: ^4.0.0
