name: fast_rx_persistence
description: An interface for implementing fast_rx key/value store persistence
version: 0.2.0
homepage: https://github.com/Rexios80/fast_ui/tree/master/fast_rx_persistence

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_rx: ^0.4.0

dev_dependencies:
  test: ^1.19.0
  rexios_lints: ^4.0.0
