name: fast_rx_shared_preferences
description: A Shared Preferences implementation of fast_rx_persistence storage for Flutter
version: 0.1.3
homepage: https://github.com/Rexios80/fast_ui/tree/master/fast_rx_shared_preferences

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_rx_persistence: ^0.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  test: ^1.21.1
  rexios_lints: ^4.0.0
  fast_rx: ^0.4.0
